AWSTemplateFormatVersion: "2010-09-09"
Description: "CodeBuild Project with GitHub"

Parameters:
  ProjectName:
    Type: String
  GitHubLocation:
    Type: String

Resources:
  ProjectRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
          PolicyName: !Join [ '', [ !Ref ProjectName, 'CodeBuildPolicy' ] ]

  BuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: "CodeBuild Project for thismichimani.net"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        Type: LINUX_CONTAINER
      Name: !Ref ProjectName
      ServiceRole: !GetAtt ProjectRole.Arn
      Source:
        Auth:
          Type: OAUTH
        Type: GITHUB
        Location: !Ref GitHubLocation
        GitCloneDepth: 1
        InsecureSsl: false
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: "^refs/heads/master$"
      TimeoutInMinutes: 10